apiVersion: v1
kind: Service
metadata:
  name: cryptonpservice-srv
spec:
  type: NodePort
  selector: 
    app: cryptocheck
  ports:
    - name: cryptocheck
      protocol: TCP
      port: 5277
      targetPort: 5277