apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailsrv
  template:
    metadata:
      labels:
        app: mailsrv
    spec:
      containers:
        - name: mailsrv
          image: majki741/api.service.mail:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mail-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mailsrv
  ports:
    - name: mailsrv
      protocol: TCP
      port: 5278
      targetPort: 5278