## kubectl create secret generic mssql-crypto --from-literal=SA_PASSWORD="password_here"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-crypto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-crypto
  template:
    metadata:
      labels:
        app: mssql-crypto
    spec:
      containers:
        - name: mssql-crypto
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-crypto
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-claim-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-crypto-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mssql-crypto
  ports:
    - name: mssql-crypto
      protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-crypto-lb-srv
spec:
  type: LoadBalancer
  selector:
    app: mssql-crypto
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433